### ISSUE TITLE
File explorer highlighted line is off

### ISSUE THREAD

**Issue by pedrohenriquegomes** [Wyliodrin/WyliodrinSTUDIO#37] opened 2017-02-08 17:49 UTC
### Description

When I open File Explorer the file list that shows on the right side is off by one line.
On the print screen you can see that the highlighted line that corresponds to the " ..(Go up)" line is above the right position.

![screenshot from 2017-02-08 09-43-06](https://cloud.githubusercontent.com/assets/2625491/22749923/cf669c5a-ede3-11e6-80a2-aa387745296f.png)

This happens on Ubuntu Linux 16.04, I have not tried on other OSes

### Version

Chrome browser: 

Version 56.0.2924.87 unknown (64-bit)

OS name:
OS version: 

Ubuntu 16.04

**Comment by serban-razvan** [comment] 2017-02-08 17:54
Duplicate of #24

**Closed** 2017-02-12 01:05 UTC
Labels: duplicate
